CONNECTION:
  ASHOST: 127.0.0.1
  SYSNR: 00
  CLIENT: 001
  USER: DEVELOPER
  PASSWD: Down1oad
  LANG: EN
FUNCTIONS:
  THUSRINFO:
  GET_CPU_ALL:
  GET_MEM_ALL:
  GET_LAN_SINGLE:
  # GET_DISK_SINGLE:
  # GET_FSYS_SINGLE:
